# Generated by Django 2.2.2 on 2019-06-25 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('contatos', models.ManyToManyField(related_name='_perfil_contatos_+', to='social_network_app.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('data', models.DateField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network_app.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=30)),
                ('data_de_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'CURTIR'), ('A', 'AMAR'), ('R', 'RIR'), ('S', 'SURPRESA'), ('T', 'TRISTEZA'), ('R', 'RAIVA')], max_length=1)),
                ('data', models.DateField()),
                ('peso', models.IntegerField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network_app.Perfil')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network_app.Postagem')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network_app.Usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network_app.Perfil')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network_app.Postagem')),
            ],
        ),
    ]
